# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana1.ui'
#
# Created: Tue Jul 08 15:51:34 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ventana(object):
    def setupUi(self, ventana):
        ventana.setObjectName(_fromUtf8("ventana"))
        ventana.setWindowModality(QtCore.Qt.NonModal)
        ventana.resize(1050, 518)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventana.sizePolicy().hasHeightForWidth())
        ventana.setSizePolicy(sizePolicy)
        ventana.setMinimumSize(QtCore.QSize(1050, 518))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/UNNe.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ventana.setWindowIcon(icon)
        ventana.setWindowOpacity(1.0)
        ventana.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        ventana.setDocumentMode(False)
        ventana.setTabShape(QtGui.QTabWidget.Rounded)
        ventana.setDockNestingEnabled(False)
        ventana.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        ventana.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(ventana)
        self.centralwidget.setMinimumSize(QtCore.QSize(940, 462))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.labelcamara = QtGui.QLabel(self.centralwidget)
        self.labelcamara.setGeometry(QtCore.QRect(9, 9, 640, 480))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelcamara.sizePolicy().hasHeightForWidth())
        self.labelcamara.setSizePolicy(sizePolicy)
        self.labelcamara.setMinimumSize(QtCore.QSize(640, 480))
        self.labelcamara.setFrameShape(QtGui.QFrame.Box)
        self.labelcamara.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelcamara.setLineWidth(1)
        self.labelcamara.setMidLineWidth(0)
        self.labelcamara.setText(_fromUtf8(""))
        self.labelcamara.setAlignment(QtCore.Qt.AlignCenter)
        self.labelcamara.setObjectName(_fromUtf8("labelcamara"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(670, 9, 361, 471))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabIni = QtGui.QWidget()
        self.tabIni.setObjectName(_fromUtf8("tabIni"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabIni)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_title = QtGui.QLabel(self.tabIni)
        self.label_title.setMinimumSize(QtCore.QSize(0, 40))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 3)
        self.bot_ini = QtGui.QPushButton(self.tabIni)
        self.bot_ini.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_ini.sizePolicy().hasHeightForWidth())
        self.bot_ini.setSizePolicy(sizePolicy)
        self.bot_ini.setMinimumSize(QtCore.QSize(60, 10))
        self.bot_ini.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/iniciar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bot_ini.setIcon(icon1)
        self.bot_ini.setIconSize(QtCore.QSize(16, 16))
        self.bot_ini.setCheckable(True)
        self.bot_ini.setObjectName(_fromUtf8("bot_ini"))
        self.gridLayout_2.addWidget(self.bot_ini, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(153, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.bot_conf = QtGui.QPushButton(self.tabIni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_conf.sizePolicy().hasHeightForWidth())
        self.bot_conf.setSizePolicy(sizePolicy)
        self.bot_conf.setMinimumSize(QtCore.QSize(40, 10))
        self.bot_conf.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bot_conf.setIcon(icon2)
        self.bot_conf.setObjectName(_fromUtf8("bot_conf"))
        self.gridLayout_2.addWidget(self.bot_conf, 2, 2, 1, 1)
        self.consola = QtGui.QTextEdit(self.tabIni)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.consola.setPalette(palette)
        self.consola.setFrameShape(QtGui.QFrame.StyledPanel)
        self.consola.setFrameShadow(QtGui.QFrame.Sunken)
        self.consola.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.consola.setReadOnly(True)
        self.consola.setObjectName(_fromUtf8("consola"))
        self.gridLayout_2.addWidget(self.consola, 3, 0, 1, 3)
        self.groupBox_info = QtGui.QGroupBox(self.tabIni)
        self.groupBox_info.setObjectName(_fromUtf8("groupBox_info"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_info)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_conf_2 = QtGui.QLabel(self.groupBox_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_conf_2.sizePolicy().hasHeightForWidth())
        self.label_conf_2.setSizePolicy(sizePolicy)
        self.label_conf_2.setMinimumSize(QtCore.QSize(160, 100))
        self.label_conf_2.setText(_fromUtf8(""))
        self.label_conf_2.setObjectName(_fromUtf8("label_conf_2"))
        self.gridLayout_5.addWidget(self.label_conf_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_info, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tabIni, icon1, _fromUtf8(""))
        self.tabConf = QtGui.QWidget()
        self.tabConf.setObjectName(_fromUtf8("tabConf"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabConf)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_conf = QtGui.QGroupBox(self.tabConf)
        self.groupBox_conf.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_conf.sizePolicy().hasHeightForWidth())
        self.groupBox_conf.setSizePolicy(sizePolicy)
        self.groupBox_conf.setCheckable(False)
        self.groupBox_conf.setObjectName(_fromUtf8("groupBox_conf"))
        self.label_hist = QtGui.QLabel(self.groupBox_conf)
        self.label_hist.setGeometry(QtCore.QRect(11, 24, 100, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hist.sizePolicy().hasHeightForWidth())
        self.label_hist.setSizePolicy(sizePolicy)
        self.label_hist.setMinimumSize(QtCore.QSize(100, 50))
        self.label_hist.setMaximumSize(QtCore.QSize(16777215, 380))
        self.label_hist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_hist.setText(_fromUtf8(""))
        self.label_hist.setScaledContents(True)
        self.label_hist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hist.setObjectName(_fromUtf8("label_hist"))
        self.gridLayout_3.addWidget(self.groupBox_conf, 3, 0, 1, 1)
        self.pushButton_conf = QtGui.QPushButton(self.tabConf)
        self.pushButton_conf.setCheckable(True)
        self.pushButton_conf.setObjectName(_fromUtf8("pushButton_conf"))
        self.gridLayout_3.addWidget(self.pushButton_conf, 2, 0, 1, 1)
        self.label_conf = QtGui.QLabel(self.tabConf)
        self.label_conf.setMinimumSize(QtCore.QSize(0, 30))
        self.label_conf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_conf.setText(_fromUtf8(""))
        self.label_conf.setObjectName(_fromUtf8("label_conf"))
        self.gridLayout_3.addWidget(self.label_conf, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabConf, icon2, _fromUtf8(""))
        self.tabRes = QtGui.QWidget()
        self.tabRes.setObjectName(_fromUtf8("tabRes"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabRes)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_res = QtGui.QGroupBox(self.tabRes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_res.sizePolicy().hasHeightForWidth())
        self.groupBox_res.setSizePolicy(sizePolicy)
        self.groupBox_res.setMinimumSize(QtCore.QSize(330, 160))
        self.groupBox_res.setObjectName(_fromUtf8("groupBox_res"))
        self.label_res_1 = QtGui.QLabel(self.groupBox_res)
        self.label_res_1.setGeometry(QtCore.QRect(15, 22, 301, 21))
        self.label_res_1.setObjectName(_fromUtf8("label_res_1"))
        self.label_res_2 = QtGui.QLabel(self.groupBox_res)
        self.label_res_2.setGeometry(QtCore.QRect(15, 50, 301, 21))
        self.label_res_2.setObjectName(_fromUtf8("label_res_2"))
        self.gridLayout_4.addWidget(self.groupBox_res, 0, 0, 1, 3)
        self.bot_video = QtGui.QPushButton(self.tabRes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_video.sizePolicy().hasHeightForWidth())
        self.bot_video.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bot_video.setIcon(icon3)
        self.bot_video.setCheckable(True)
        self.bot_video.setObjectName(_fromUtf8("bot_video"))
        self.gridLayout_4.addWidget(self.bot_video, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.bot_curvas = QtGui.QPushButton(self.tabRes)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/curva.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bot_curvas.setIcon(icon4)
        self.bot_curvas.setCheckable(True)
        self.bot_curvas.setObjectName(_fromUtf8("bot_curvas"))
        self.gridLayout_4.addWidget(self.bot_curvas, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabRes, icon4, _fromUtf8(""))
        self.tabDat = QtGui.QWidget()
        self.tabDat.setObjectName(_fromUtf8("tabDat"))
        self.comboBox = QtGui.QComboBox(self.tabDat)
        self.comboBox.setGeometry(QtCore.QRect(110, 80, 75, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.lineEdit = QtGui.QLineEdit(self.tabDat)
        self.lineEdit.setGeometry(QtCore.QRect(110, 20, 221, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton = QtGui.QPushButton(self.tabDat)
        self.pushButton.setGeometry(QtCore.QRect(20, 400, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tabDat)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 400, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label = QtGui.QLabel(self.tabDat)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_6 = QtGui.QLabel(self.tabDat)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabDat)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 50, 221, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_7 = QtGui.QLabel(self.tabDat)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tabDat)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.textEdit = QtGui.QTextEdit(self.tabDat)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 321, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_9 = QtGui.QLabel(self.tabDat)
        self.label_9.setGeometry(QtCore.QRect(10, 190, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEdit_2 = QtGui.QTextEdit(self.tabDat)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 210, 321, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_10 = QtGui.QLabel(self.tabDat)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tabDat)
        self.label_11.setGeometry(QtCore.QRect(10, 310, 91, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabDat)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 280, 221, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tabDat)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 310, 221, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/datos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabDat, icon5, _fromUtf8(""))
        ventana.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ventana)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 20))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOpciones = QtGui.QMenu(self.menubar)
        self.menuOpciones.setObjectName(_fromUtf8("menuOpciones"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setSeparatorsCollapsible(False)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        ventana.setMenuBar(self.menubar)
        self.actionGuardar = QtGui.QAction(ventana)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionCargar = QtGui.QAction(ventana)
        self.actionCargar.setObjectName(_fromUtf8("actionCargar"))
        self.actionCerrar = QtGui.QAction(ventana)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionInstrucciones = QtGui.QAction(ventana)
        self.actionInstrucciones.setObjectName(_fromUtf8("actionInstrucciones"))
        self.actionAcerca = QtGui.QAction(ventana)
        self.actionAcerca.setObjectName(_fromUtf8("actionAcerca"))
        self.actionContacto = QtGui.QAction(ventana)
        self.actionContacto.setObjectName(_fromUtf8("actionContacto"))
        self.actionAp2 = QtGui.QAction(ventana)
        self.actionAp2.setObjectName(_fromUtf8("actionAp2"))
        self.menuOpciones.addAction(self.actionGuardar)
        self.menuOpciones.addAction(self.actionCargar)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionCerrar)
        self.menuAyuda.addAction(self.actionInstrucciones)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionContacto)
        self.menubar.addAction(self.menuOpciones.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(ventana)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ventana)

    def retranslateUi(self, ventana):
        ventana.setWindowTitle(_translate("ventana", "Analizador de marcha", None))
        self.label_title.setText(_translate("ventana", "<html><head/><body><p>Laboratorio de marchas 1.0- UNNe </p></body></html>", None))
        self.bot_ini.setText(_translate("ventana", "Iniciar", None))
        self.bot_conf.setText(_translate("ventana", "Configuración", None))
        self.groupBox_info.setTitle(_translate("ventana", "Configuración Actual:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIni), _translate("ventana", "Iniciar", None))
        self.groupBox_conf.setTitle(_translate("ventana", "  Configuración Actual:", None))
        self.pushButton_conf.setText(_translate("ventana", "Configurar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConf), _translate("ventana", "Configuración", None))
        self.groupBox_res.setTitle(_translate("ventana", "Resumen", None))
        self.label_res_1.setText(_translate("ventana", "Velocidad [Mts/Seg]:", None))
        self.label_res_2.setText(_translate("ventana", "Distancia de paso [Metros]:", None))
        self.bot_video.setText(_translate("ventana", "Ver Video", None))
        self.bot_curvas.setText(_translate("ventana", "Ver Curvas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRes), _translate("ventana", "Resultados", None))
        self.comboBox.setItemText(0, _translate("ventana", "Masculino", None))
        self.comboBox.setItemText(1, _translate("ventana", "Femenino", None))
        self.pushButton.setText(_translate("ventana", "Cargar", None))
        self.pushButton_2.setText(_translate("ventana", "Guardar", None))
        self.label.setText(_translate("ventana", "Nombre y apellido:", None))
        self.label_6.setText(_translate("ventana", "Edad (años):", None))
        self.label_7.setText(_translate("ventana", "Sexo:", None))
        self.label_8.setText(_translate("ventana", "Sintoma:", None))
        self.label_9.setText(_translate("ventana", "Diagnostico:", None))
        self.label_10.setText(_translate("ventana", "Profesional:", None))
        self.label_11.setText(_translate("ventana", "Fecha y hora:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDat), _translate("ventana", "Datos", None))
        self.menuOpciones.setTitle(_translate("ventana", "Opciones", None))
        self.menuAyuda.setTitle(_translate("ventana", "Ayuda", None))
        self.actionGuardar.setText(_translate("ventana", "Cargar Datos", None))
        self.actionCargar.setText(_translate("ventana", "Cargar Configuración", None))
        self.actionCerrar.setText(_translate("ventana", "Cerrar", None))
        self.actionInstrucciones.setText(_translate("ventana", "instrucciones", None))
        self.actionAcerca.setText(_translate("ventana", "Acerca del brazo", None))
        self.actionContacto.setText(_translate("ventana", "Contacto", None))
        self.actionAp2.setText(_translate("ventana", "Aplicación 2", None))

